### ISSUE TITLE
Flatdoc을 써서 문서를 더 예쁘게

### ISSUE THREAD

**Issue by item4** [swmaestro/somat#19]
[flatdoc](https://github.com/rstacruz/flatdoc)을 쓰면 어떨까요?

적어도 개발자 센스로 한 디자인보단 저게 더 예뻐보입니다.

**Comment by darjeeling** [comment]
ok. give me a pr

**Comment by item4** [comment]
이미 다른 방법으로 예뻐졌으므로 닫습니다
