### ISSUE TITLE
default branch를 gh-pages로 만드는 것은 어떤가요

### ISSUE THREAD

**Issue by disjukr** [swmaestro/somat#2]
`index.html`에서 `README.md`를 읽어와서 예쁘게 보여주면 좋을 것 같네요.

**Comment by dobestan** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by LyuGGang** [comment]
+1

**Comment by darjeeling** [comment]
@disjukr  이분께서 pr 주신답니다.

**Comment by item4** [comment]
@disjukr PR 기대합니다

**Comment by disjukr** [comment]
와 졸리당 http://swmaestro.github.io/somat/
아무나 바톤 넘깁니다.

검색기능 같은거 구현되면 좋을 것 같네요.
css도 좀 발라야겠고 ㄹㄹ..
